TestGrepError: Update git error message 'fatal: no pattern given'
- with newer git (v2.19.1) this message skips the ending '.'
- this message has been changed in the past
https://github.com/git/git/commit/1a07e59c3e269418f3f5d186d166bf5ab5db6667

Signed-off-by: Andras Mitzki <mitzkia@gmail.com>